version: "3.9"
services:
  chatgpt-next-web:
    container_name: chatgpt-next-web
    # ğŸ‘‡ å¿…é¡»å’Œä¸Šé¢ Action é‡Œçš„åå­—ä¸€æ¨¡ä¸€æ ·
    image: ghcr.io/usagisean/nextchat:latest
    ports:
      - 3000:3000
    environment:
      # ğŸ”´ å¿…é¡»å¡«ä½ çš„ New API (One API) åœ°å€ï¼Œå¦åˆ™æ— æ³•è®¡è´¹
      - BASE_URL=https://api.zixiang.us
      
      # ğŸ”´ å¿…é¡»è®¾ä¸€ä¸ªä¹±ç å¯†ç ï¼Œä¸ºäº†è§¦å‘ä½ ä¿®æ”¹è¿‡çš„â€œæ‹¦æˆªé¡µâ€
      - CODE=random_password_to_force_auth_page
      
      # âœ… å…è®¸ç”¨æˆ·å¡« Key
      - HIDE_USER_API_KEY=0
      
      # å…¶ä»–é»˜è®¤é…ç½®
      - OPENAI_API_KEY=$OPENAI_API_KEY
      - DISABLE_GPT4=$DISABLE_GPT4
      - ENABLE_BALANCE_QUERY=$ENABLE_BALANCE_QUERY
      - DISABLE_FAST_LINK=$DISABLE_FAST_LINK
    restart: always