version: "3.9"
services:
  chatgpt-next-web:
    container_name: next-chat
    image: ghcr.io/usagisean/nextchat:latest
    ports:
      # ✅ 【核心修复】改为 3002，避开 OpenWebUI 的 3000
      - 3002:3000
    environment:
      - BASE_URL=https://ai.zixiang.us
      - CODE=zixiang_ai_888
      - HIDE_USER_API_KEY=0
      - OPENAI_API_KEY=$OPENAI_API_KEY
      - DISABLE_GPT4=$DISABLE_GPT4
      - ENABLE_BALANCE_QUERY=$ENABLE_BALANCE_QUERY
      - DISABLE_FAST_LINK=$DISABLE_FAST_LINK
    restart: always